### ISSUE TITLE
Provide compatibility for log4j versions prior to 1.2.15

### ISSUE THREAD

**Issue by mjizadi** [mbizhani/web4log#1]
The "application" field used in web4log was added in log4j version 1.2.15 and therefore it can't operate with applications using older versions. We can use an "untitled"-like name (with numbers to avoid duplication) to use with appenders that are conected with no application specified.

**Comment by mbizhani** [comment]
The "application" field helps the user to recognize what application has connected to the Web4Log, and on reconnection it also helps to detect the previously connected application. In your proposal, on reconnection, Web4Log recognizes it as another untitled application.
